spring :
  datasource :
    driverClassName : org.hsqldb.jdbcDriver
    url : jdbc:hsqldb:databaseHSQLDB/BelajarTesting

  jpa :
    hibernate :
      ddl-auto : update

server :
  port : 8888
  context-path : /BelajarLogging
  
# LOGGING
logging.path : 
logging.file : LoggingAplikasi.log
logging.config : classpath:log4j.properties
logging.level.com.rizki.mufrizal: DEBUG 
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR