spring :
  datasource :
    driverClassName : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/BelajarTesting
    username : rizki
    password : mufrizal

  jpa :
    hibernate :
      ddl-auto : update

server :
  port : 8888
  context-path : /BelajarLogging
  
# LOGGING
logging.path : 
logging.file : LoggingAplikasi.log
logging.config : classpath:log4j.properties
logging.level.com.rizki.mufrizal: DEBUG 
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR